### ISSUE TITLE
Description field should support markdown link pattern

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#8]
Currently `<a>` tag in description works but markdown link pattern `[LinkName](linkUrl)` is not working.

**Comment by yorkie** [comment]
In fact, the markdown syntax detection and rendering has been implemented at `classes` view by YUIDoc itself, this bug seems to be reproduced at `modules` view that is created by us, now I introduced this feature at `modules` view via 00faf69. Let me know if this feature still not yet got correctly in your builds. Thank you!!!

/cc @nantas
